standard_urls = ['https://numeroscop.net/angel-numbers/@#$-angel-number.html', 'https://www.sunsigns.org/angel-number-@#$-meaning/']
non_standard_urls = {555:['cndss.com',]}    #{angel_numbers:[value1,value2]}
xpaths = '//*[@id="ez-toc-container"]'
remove_attribute = [('id',['ez-toc-container','dpsp-floating-sidebar','comments','dpsp-content-bottom']),('class',['main-header-bar-wrap','purplebox','pinkbox','trail-items','class','skip-link screen-reader-text','entry-meta','yellowbox','tablelinks','saboxplugin-wrap','emalsubinpt','dpsp-share-text','nav-links','screen-reader-text','dpsp-share-text ','n-square'])]
para_wise_delim = '@@@@@@@@@@@@@@@@@@@'
page_xpath = [('https://hiddennumerology.com',"//main[@id='main']"),('https://numeroscop.net',"//section[@class='text']")]
page_wise_delimeter = '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'

urls = {'1':["https://www.adviseastro.com/angel-number-838-meaning-and-symbolism/"], '2': ['https://angelmanifest.com/angel-number-646/'], '3': ["https://angelnumber.me/1033-meaning/"],
        '4': ["https://angelnumber.org/7747-angel-number/","https://angelnumber.org/555-angel-number-meaning-and-symbolism/"],'5': ["https://angelnumbersmeaning.com/0001-angel-number/","https://angelnumbersmeaning.com/angel-number-0101-meaning-and-symbolism/","https://angelnumbersmeaning.com/angel-number-1055/"],
        '6': ["https://www.angelsnumbers.com/meaning/number-741/"], '7': ["https://www.coolastro.com/angel-number-1001-meaning-and-symbolism/"], '8': ["https://divineangelnumbers.com/203-angel-number-meaning","https://divineangelnumbers.com/angel-number-711-meaning","https://divineangelnumbers.com/angel-number-13-meaning","https://divineangelnumbers.com/angel-number-7474","https://divineangelnumbers.com/73-angel-number"],
        '9': ["https://www.guardian-angel-reading.com/blog-of-the-angels/999-angel-number/","https://www.guardian-angel-reading.com/blog-of-the-angels/angel-number-0/","https://www.guardian-angel-reading.com/blog-of-the-angels/2022-angel-number-meaning/"],
        '10': ["https://hiddennumerology.com/angel-number-0000/"], '11': ["https://www.ipublishing.co.in/angel-number-8888-meaning","https://www.ipublishing.co.in/angel-number-8"], '12': ["https://joynumber.com/212-angel-number/","https://joynumber.com/angel-number-17/","https://joynumber.com/7777-angel-number-meaning/"],
        '13': ["https://mattbeech.com/repeating-numbers/666-meaning/"], '14': ["https://www.mindbodygreen.com/articles/1144-angel-number","https://www.mindbodygreen.com/articles/222-angel-number-meaning"], '15': ["https://www.mindfulnessandjustice.org/angel-number-711/","https://www.mindfulnessandjustice.org/angel-number-711-meaning/"],
        '16': ["https://www.mindyourbodysoul.com/1717-angel-number/","https://www.mindyourbodysoul.com/angel-number-1/"],'17': ["https://numerologynation.com/13-angel-number/","https://numerologynation.com/angel-number-0/"],'18': ["https://numerologysign.com/angel-number-37-meanings/"],
        '19': ["https://www.psychnewsdaily.com/1111-angel-number-meaning/"], '20': ["https://www.ryanhart.org/angel-number-911-meaning/"],
        '21': ["http://sacredscribesangelnumbers.blogspot.com/2019/01/angel-number-3362.html","http://sacredscribesangelnumbers.blogspot.com/2018/12/angel-number-3316.html","http://sacredscribesangelnumbers.blogspot.com/2018/05/angel-number-3311.html","http://sacredscribesangelnumbers.blogspot.com/2018/04/angel-number-3311.html"],
        '22': ["https://takanta.com/606-angel-number","https://takanta.com/angel-number-66"], '23': ["https://thesecretofthetarot.com/angel-number-9999/"], '24': ["https://trustedpsychicmediums.com/angel-numbers/angel-number-5000/"], '25': ["https://www.yummymummykitchen.com/2022/03/444-angel-number-meaning.html","https://www.yummymummykitchen.com/2021/10/angel-numbers.html"]}