remove_attribute = {'https://angelnumber.org': {'id': ['M381992ScriptRootC303780','ez-video-wrap-b4ec00c06bec2bc40ada432314eccc6f73f68ab435b952b516c17921ed16f3d3'],'class': ['hm-related-posts','cat-links','navigation post-navigation','remove-element']},
                    'https://angelmanifest.com': {'class': ['wp-block-embed is-type-wp-embed is-provider-angel-manifest wp-block-embed-angel-manifest','entry-meta','ct-breadcrumbs'],'id':['ez-toc-container','Also_Read'], 'href': ['https://angelmanifest.com/angel-numbers/']},
                    'https://www.angelsnumbers.com/':{'id': ['le_body_row_8'], 'class': ['op-custom-html-block','breadcrumb-style-7']},
                    'https://www.coolastro.com/':{'id': ['comments','ez-toc-container'], 'class': ['entry-meta','relpost-thumb-wrapper']},
                    'https://divineangelnumbers.com/':{'id':['comments', 'grow-me-in-content-recs-root'],'class': ['uagb-toc__wrap', 'entry-category-icon', 'entry-meta clear', 'social-share-icons', 'has-background','author-box clear', 'entry-related clear', 'wp-block-image']},
                    'https://www.guardian-angel-reading.com/': {'id': ['share'],'class': ['related-articles fixedfont','homeform homeform--og ', 'byline author vcard','homefooter__socialbuttons homefooter__socialbuttons--posts fixedfont']},
                    'https://hiddennumerology.com/': {'id': ['ez-toc-container', 'dpsp-content-bottom', 'grow-me-in-content-recs-root','comments'], 'class':['purplebox','pinkbox','yellowbox','yellowcta', 'emalsubinpt', 'saboxplugin-tab', 'dpsp-share-text ', 'navigation post-navigation', 'tablelinks','entry-meta'],'href': ['https://hiddennumerology.com/printables-on-etsy']},
                    'https://www.adviseastro.com' : {'id':['ez-toc-container'],'class':['entry-meta']},
                    'https://www.ipublishing.co.in/' : {'id':['toc_container'],'class':['entry-meta']},
                    'https://joynumber.com/' : {'id':['toc_container'],'class':['css-ujfvsi eods1cv1','css-v5rwlu eods1cv8','css-nq5slz e16ntblo5','css-75up63 e1nq2w9512', 'css-19p6q85 ecyq0i81','remove-element'],'role':['complementary']}, #problem in 777
                    'https://mattbeech.com/' : {'id':['toc_container', 'single-comments','main-nav','Other_Repeating_Numbers','Learn_the_meanings_of_other_angel_numbers'],'class':['breadcrumb','nav','col-12 col-lg-4 copyright','remove-element'],'data-type':['URL','page']},  #need replace_code
                    'https://www.mindbodygreen.com/' : {'class':['subcategory-label c-dark-purple ', 'editor-info__text', 'article-subnavigation', 'ad__callout container', 'article-header__share-like article-header__share-like--standard  article-header__share-like--p2', 'article-image article-image--p1 article-image--hero article-image--hero-standard ', 'article-affiliate-disclaimer', 'article-date article-date--standard', 'article-header__share-like-wrapper', 'article-header__share-like-wrapper article-header__share-like-wrapper--alt']},
                    'https://www.mindfulnessandjustice.org/' : {'class':['remove-element','saboxplugin-wrap', 'entry-meta', 'InlineRecs___StyledDiv3-sc-7gga64-8 kMYAEH', 'code-block code-block-1','code-block code-block-2'],'id':['selection_bubble',]},
                    'https://trustedpsychicmediums.com':{'class':['entry-meta','irp','entry-author author-bottom','tag-cloud','entry-related-posts','entry-actions','screen-reader-text'],'itemprop':['articleSection'],'id':['toc_container','respond','entry-actions','entry-related-posts','comments']}, #24
                    'https://numerologycolumn.com/' : {'id':['toc_container'],'class':['code-block code-block-1','author-card', 'recent-articles-container', 'entry-meta sr-only'],'href':["https://numerologist.com/anf-mesl/denpet"]}, #17
                    'https://numerologynation.com/' : {'id':['toc_container'],'class':['ck_form', 'entry-meta', 'rank-math-breadcrumb','remove-element']},
                    'https://numerologysign.com/' : {'id':['mv-trellis-comments'],'class':['article-meta post-meta-wrapper post-meta-single post-meta-single-top', 'su-button-center', 'ShadowDomContainer___StyledDiv-paiu0k-0', 'entry-footer', 'navigation post-navigation']},
                    'https://www.psychnewsdaily.com/' : {'id': ['more-information-about-what-angel-numbers-mean','extra-more-information-about-what-angel-numbers-mean','check-out-our-guides-to-other-popular-angel-numbers','read-our-other-articles-about-angel-numbers'],'class':['author-box ct-hidden-sm', 'simpletoc-title', 'adthrive-player-title', 'remove-element','page-description ct-hidden-sm']},
                    'https://www.ryanhart.org/' : {'class':['remove-element','post-comments', 'center w-100 br3 hidden ba b--grey-3 mv4', 'mw7 center', 'mw7 mv4 center sans-serif tc', 'f7 grey-3 sans-serif', 'f7 flex justify-between grey-3 sans-serif','remove-element'],'rel':['nofollow']},
                    'http://sacredscribesangelnumbers.blogspot.com' : {'class':['post-footer', 'MsoNormal'], 'href': ['https://www.etsy.com/au/shop/JoWPottery','http://numerology-thenumbersandtheirmeanings.blogspot.com/', 'http://www.facebook.com/JoWPottery/', 'http://sacredscribes.blogspot.com.au/p/about-joanne-sacred-scribes.html', 'http://sacredscribes.blogspot.com.au/2016/10/joanne-sacred-scribes-websites-blogs.html', 'https://sacredscribesangelnumbers.blogspot.com/p/get-psychic-reading-for-199.html','http://www.instagram.com/sacredscribes_jowpottery/','https://trykeen.com/sacredscribes']},
                    'https://numeroscop.net/': {'class':['header', 'n-square', 'angel-realted-posts','num-preproc-hlt']},
                    'https://researchmaniacs.com/': {'id': ['177976545'],'class':['header', 'n-square', 'angel-realted-posts', 'remove-element']},
                    'https://www.sunsigns.org/': {'id':[''], 'class': ['single-post-video', 'post-meta', 'share-post']},
                    'https://www.mindyourbodysoul.com': {'id':['comment-count', 'cls-video-container-wqZUnNP4', 'mv-trellis-comments', 'dpsp-content-top'], 'class': ['lwptoc_i', 'entry-footer', 'share-post']},
                    'https://willowsoul.com/': {'id': ['comments'], 'class': ['remove-element', 'clearfix', 'table-wrapper', 'social-sharing normal','author']},
                    'https://www.yummymummykitchen.com/': {'id': ['dpsp-content-top','dpsp-content-bottom','grow-me-inline-subscribe-cta-root-0'], 'class': ['post-meta post-date', 'post-meta', 'post-meta meta-centered','remove-element'], 'href': ['http://amazon.com/Angel-Numbers-101-Meaning-Sequences/dp/1401920012','http://amazon.com/gp/product/1788173473']},
                    'https://www.thepubliclive.com/': {'class': ['head angel-number', 'post-bottom clear-block', 'story-fb-twitter clear-block','author','fb-comment clear-block','postmetadata']},
                    'https://angelnumbersmeaning.com': {'id': ['M319879ScriptRootC214660_03376'],'class':['remove-element','ezoic-ad nativedouble-1 nativedouble-1110 adtester-container adtester-container-110', 'relpost-thumb-wrapper', 'ez-report-ad-button','meta-category']},
                    'https://thesecretofthetarot.com/': {'id': ['ez-toc-container'], 'class': ['dpsp-share-text ','entry-header', 'p1', 'rp4wp-related-posts','remove-element'],'rel':['”nofollow'], 'href': ['https://thesecretofthetarot.com/reading']},
                    'https://takanta.com/': {'id':['ez-toc-container'],'class': ['entry-meta']},
                    'https://angelnumber.me': {'id':['toc_container','Frequently-Asked-Questions-FAQs'], 'class': ['ast-breadcrumbs-wrapper']}
                    }

page_xpath = [('https://hiddennumerology.com',"//main[@id='main']"),  #10
              ('https://www.adviseastro.com',"//div[@class='inside-article']"),  #1
              ('https://angelmanifest.com',"//div[@class='hero-section']|//div[@class='entry-content']"),  #2
              ('https://angelnumber.org/', '//*[@id="main"]'),  #4
              ('https://angelnumbersmeaning.com/', '//*[@id="main"]'),  #5
              ('https://www.angelsnumbers.com/', '//*[@id="content_area"]'),  #6
              ('https://www.coolastro.com/','//*[@id="primary"]'),  #7
              ('https://divineangelnumbers.com/','//*[@id="main"]'),  #8
              ('https://www.guardian-angel-reading.com/','//*[@id="sticky-anchor"]/div/main'),
              ('https://angelnumber.me','//*[@id="primary"]'),  #3
              ('https://www.ipublishing.co.in/','//*[@class="inside-article"]'),  #11
              ('https://joynumber.com/', '//article'), # 12
              ("https://mattbeech.com/",'//*[@class="container"]'), #13
              ("https://www.mindbodygreen.com/",'//*[@class="main-content__article-body"]'), #14
              ("https://www.mindfulnessandjustice.org/",'//*[@id="main"]'), #15
              ('https://trustedpsychicmediums.com',"//main[@id= 'main']"),
              ('https://www.mindyourbodysoul.com',"//main[@id='content']"),
              ('https://numerologycolumn.com/',"//main[@id= 'main']"), #25
              ('https://numerologynation.com/',"//div[@class= 'inside-article']"), #17
              ('https://numerologysign.com/',"//*[@id='content']"), #18
              ('https://www.psychnewsdaily.com/','//*[@id="main"]'), #19
              ('https://www.ryanhart.org/','//*[@class="fl mw6 ph2 pv2 cms"]'),
              ('http://sacredscribesangelnumbers.blogspot.com','//*[@class="post hentry uncustomized-post-template"]'),
              ('https://numeroscop.net/','//main[@class= "container body"]'),
              ('https://researchmaniacs.com/','//div[@class= "title" ] | //div[@class= "content"]'),
              ('https://www.sunsigns.org/','//*[@id="the-post"]'),
              ('https://willowsoul.com/','//*[@id="shopify-section-article-template"]'),
              ('https://www.yummymummykitchen.com/', '//*[@id="content"]/article'),
              ('https://www.thepubliclive.com/','//*[@class="container bdr m-pad-t-0 clear-block"]'),
              ('https://thesecretofthetarot.com/','//*[@id="main"]'),
              ('https://takanta.com/','//div[@class="inside-article"]') #22
              ]
ignore_tag_by_domain = {'https://angelmanifest.com': ['ul'],
                        'https://www.psychnewsdaily.com': ['ul'],
                        'https://numeroscop.net': ['nav', 'aside'],
                        'https://researchmaniacs.com': ['font'],
                        'https://www.sunsigns.org': ['ul', 'center', 'form'],
                        'https://www.mindyourbodysoul.com': ['nav'],
                        'https://willowsoul.com/': ['aside', 'time'],
                        'https://www.thepubliclive.com/': ['ol', 'ul'],
                        'https://www.guardian-angel-reading.com/': ['ul'],
                        'https://angelnumbersmeaning.com': ['footer','ul'],
                        'https://thesecretofthetarot.com/': ['footer','ul'],
                        'https://takanta.com/': ['footer','h5'],
                        'https://www.coolastro.com/': ['ul'],
                        'https://numerologysign.com/': ['ul'],
                        'https://mattbeech.com/': ['ul'],
                        'https://hiddennumerology.com/':['blockquote'],
                        'https://numerologynation.com/': ['ul']}
page_wise_delimeter = '$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$'
para_wise_delim = '@@@@@@@@@@@@@@@@@@@'
ignore_site_num = [17]
url_patterns = {'1':  ["https://www.adviseastro.com/angel-number-@#$-meaning-and-symbolism/"],
        '2':  ['https://angelmanifest.com/angel-number-@#$/'],
        '3':  ["https://angelnumber.me/@#$-meaning/"],    #no remove attribute need to add for this page
        '4':  ["https://angelnumber.org/@#$-angel-number/","https://angelnumber.org/@#$-angel-number-meaning-and-symbolism/"],
        '5':  ["https://angelnumbersmeaning.com/@#$-angel-number/","https://angelnumbersmeaning.com/angel-number-@#$-meaning-and-symbolism/","https://angelnumbersmeaning.com/angel-number-@#$/"],
        '6':  ["https://www.angelsnumbers.com/meaning/number-@#$/"],
        '7':  ["https://www.coolastro.com/angel-number-@#$-meaning-and-symbolism/"],
        '8':  ["https://divineangelnumbers.com/@#$-angel-number-meaning","https://divineangelnumbers.com/angel-number-@#$-meaning","https://divineangelnumbers.com/angel-number-@#$-meaning","https://divineangelnumbers.com/@#$-angel-number","https://divineangelnumbers.com/angel-number-@#$/"],
        '9':  ["https://www.guardian-angel-reading.com/blog-of-the-angels/@#$-angel-number/","https://www.guardian-angel-reading.com/blog-of-the-angels/@#$-angel-number-meaning/","https://www.guardian-angel-reading.com/blog-of-the-angels/angel-number-@#$/"],
        '10': ["https://hiddennumerology.com/angel-number-@#$/"],
        '11': ["https://www.ipublishing.co.in/angel-number-@#$-meaning","https://www.ipublishing.co.in/angel-number-@#$/"],
        '12': ["https://joynumber.com/@#$-angel-number/","https://joynumber.com/@#$-angel-number-meaning/","https://joynumber.com/angel-number-@#$/"],
        '13': ["https://mattbeech.com/repeating-numbers/@#$-meaning/"],
        '14': ["https://www.mindbodygreen.com/articles/@#$-angel-number-meaning", "https://www.mindbodygreen.com/articles/@#$-angel-number"],
        '15': ["https://www.mindfulnessandjustice.org/angel-number-@#$-meaning/","https://www.mindfulnessandjustice.org/angel-number-@#$/"],
        '16': ["https://www.mindyourbodysoul.com/@#$-angel-number/","https://www.mindyourbodysoul.com/angel-number-@#$/"],
        '17': ["https://numerologynation.com/@#$-angel-number/","https://numerologynation.com/angel-number-@#$/"],
        '18': ["https://numerologysign.com/angel-number-@#$-meanings/"],
        '19': ["psychnewsdaily.csv"], #manual csv
        '20': ["https://www.ryanhart.org/angel-number-@#$-meaning/"],
        '21': ["sacredscribesangelnumbers.csv"],
        '22': ["takanta.csv"],
        '23': ["https://thesecretofthetarot.com/angel-number-@#$/"],
        '24': ["https://trustedpsychicmediums.com/angel-numbers/angel-number-@#$/"],
        '25': ["https://numerologycolumn.com/@#$-angel-number/","https://numerologycolumn.com/angel-number-@#$-numerology-meaning/","https://numerologycolumn.com/angel-number-@#$/"],
        '26': ["https://numeroscop.net/angel-numbers/@#$-angel-number.html"],
        '27': ["https://researchmaniacs.com/Numerology/Angel-Numbers/Angel-Number-@#$.html"],
        '28': ["https://www.sunsigns.org/angel-number-@#$-meaning/","https://www.sunsigns.org/angel-number-@#$/"],
        '29': ['willowsoul.csv'],
        '30': ['yummymummykitchen.csv'],
        '31': ['thepublic.csv']}


remove_code = {'https://hiddennumerology.com':[{'orig':'<h3>Read the meaning of the other Angel Numbers</h3>', 'new':''}],
               'https://angelmanifest.com':[{'orig': '<h3>Other Angel Numbers:</h3>','new':''},
                                            {'orig': '<p>Also read:</p>','new': ''},
                                            {'orig': '<h2>Also Read:</h2>', 'new':''},
                                            {'orig': '<h3>Also Read:</h3>', 'new':''},
                                            {'orig': '<p>Angel Number list</p>', 'new':''},
                                            {'orig': '<p>Thank you for reading this article.</p>', 'new': ''}],
               'https://numerologycolumn.com/':[{'orig':'<h3 class="h2">Recent Posts</h3>', 'new': ''},
                                                {'orig':'<h2>Related posts</h2>', 'new': ''},
                                                ],
               'https://numerologynation.com/':[{'orig':'<p><strong>Read More','new':'<p class ="remove-element"><strong>Read More'}],
               'http://sacredscribesangelnumbers.blogspot.com': [{'orig':'<span ', 'new': '<p '},
                                                                 {'orig':'</span', 'new': '</p '},
                                                                 {'orig': '*', 'new' : ''},
                                                                 {'orig': '... click', 'new': ''},
                                                                 {'orig': 'Also see:', 'new': ''},
                                                                 {'orig': 'for further information.', 'new': ''}],
               'https://researchmaniacs.com/':[{'orig': '<b>Important Notes:</b>', 'new':''},
                                            {'orig': "<br/>\nOlga\'s interpretations and opinons about the Angel Number", 'new':"<p class = 'remove-element'>\nOlga\'s interpretations and opinons about the Angel Number 777"},
                                            {'orig': "<br/>\nHere is the next Angel Number on Olga\'s list that she has interpreted.<br/>",'new':''},
                                            {'orig': "<br/>\nThis is Olga's view of Angel Number",'new':"<p class = 'remove-element'>\nThis is Olga's view of Angel Number"},
                                            {'orig': '<br/><br/>','new':'</p><p>'},
                                            {'orig': '<br\>','new': '<p>'},
                                            {'orig': '</br>','new': '<p>'},
                                            {'orig': '<b>', 'new':'<h4>'},
                                            {'orig': '</b>', 'new':'</h4>'},
                                            {'orig':'You can look up another Angel Number here:','new':''},
                                            {'orig': 'Olga', 'new':'Bridget'},],
               'https://www.sunsigns.org': [{'orig': '<strong>See Also:</strong>','new':''}],
               'https://joynumber.com/': [{'orig': '<h2 id="archived-comments"','new':'<div class = "remove-element" ><h2 id="archived-comments"'},
                                          {'orig': '</article>','new':'</div></article>'}],
               'https://willowsoul.com': [{'orig': '</header>\n\n        <p>', 'new': '</header>\n\n        <p class = "remove-element">'},
                                          {'orig': "<p><span>PUBLISHER", 'new': "<p class = 'remove-element'><span>PUBLISHER"},
                                          {'orig': "<p>PUBLISHER", 'new': "<p class = 'remove-element'>PUBLISHER"}],
               'https://www.yummymummykitchen.com':[{'orig': '<p>Sources: </p>', 'new': ''},
                                                    {'orig':'<h2>More Common Angel Numbers &amp; Their Meanings </h2>', 'new': ''},
                                                    {'orig':'<h2>MORE COMMON ANGEL NUMBER SEQUENCES </h2>', 'new': ''},
                                                    {'orig': '1111112210103335556661010123', 'new': ''},
                                                    {'orig': '<h2>More on Angel Numbers</h2>', 'new': ''},
                                                    {'orig': 'Angel Number Basics Angel Number 666 Number 123 Meaning1122 Meaning', 'new': ''},
                                                    {'orig': '<p>References:', 'new': '<p class = "remove-element">References:'}],
               'https://www.thepubliclive.com/':[{'orig': '@@@@@@@@@@@@@@@@@@@<p>Click Below Links To Read More Articles –</p>@@@@@@@@@@@@@@@@@@@<p>USA UK Canada Australia South Africa India</p>@@@@@@@@@@@@@@@@@@@COMMENT ', 'new': ''}],
               'https://www.guardian-angel-reading.com/': [{'orig':'<p>Table of Contents</p>', 'new': ''},
                                                           {'orig': '<h2>Discover some more interesting articles from Padre:</h2>', 'new': ''}],
               'https://angelnumbersmeaning.com': [{'orig': '<h3>Related posts:</h3>', 'new': ''},
                                                   {'orig': '<p>Read also:</p>', 'new': ''},
                                                   {'orig': 'Loading...', 'new': ''},
                                                   {'orig': '<p><strong>Watch Youtube Video About Angel Number', 'new': '<p class = "remove-element"><strong>Watch Youtube Video About Angel Number'}],
               'https://thesecretofthetarot.com': [{'orig': '<h2>Angel numbers communicated frequently:</h2>', 'new': ''},
                                                   {'orig': '<h2>Explore our in-depth guides below:</h2>', 'new': ''},
                                                   {'orig': '<strong>PSSST....Relationship Compatibility Quiz Reveals The Secrets Of His Zodiac Sign: </strong>','new': ''},
                                                   {'orig': 'PSSST: Are You Ready to Finally Meet Your True Soulmate?? Get a psychic drawing of your soulmate now!', 'new': ''},
                                                   {'orig':'<p>Additional reading:','new':'<p class="remove-element">Additional reading:'},
                                                   {'orig': 'Need guidance and clarity in love, career and more?', 'new': ''},
                                                   {'orig': 'Click Here to Get a FREE Personalized Numerology Reading!', 'new': ''},
                                                   {'orig': 'FREE GIFT:', 'new': ''}],
               'https://www.psychnewsdaily.com/': [{'orig': '<p><strong>Photo', 'new': '<p class ="remove-element"><strong>Photo'},
                                                   {'orig': '<p>Photos:', 'new': '<p class ="remove-element">Photos:'},
                                                   {'orig': '<p>Thanks for reading!</p>', 'new': ''},
                                                   {'orig': '<p>Related posts:</p>', 'new': ''},
                                                   {'orig': '<p>Find out more', 'new': '<p class = "remove-element">Find out more'},
                                                   {'orig': '<p>Think of it as your own personal blueprint to success and happiness: a blueprint that will help you live your most amazing life. Find out more here.</p>','new': ''},
                                                   {'orig': 'To lean more about angel numbers, see the below articles:', 'new': ''},
                                                   {'orig': 'Check out our guides to other popular angel numbers', 'new': ''},
                                                   {'orig': '<p>Fortunately, we can correct this right now','new':'<p class ="remove-element">Fortunately, we can correct this right now' }],
               'https://mattbeech.com/':[{'orig':' | ','new':''},
                                         {'orig': '<p>Enjoyed reading this article?', 'new': '<p class="remove-element">Enjoyed reading this article?'}],
               'https://www.mindfulnessandjustice.org/': [{'orig': '<p>if you liked this article make sure to checkout', 'new': '<p class = "remove-element">if you liked this article make sure to checkout '}],
               'https://numeroscop.net':[{'orig':'<h2>Related posts</h2>','new':''},
                                         {'orig':'<h3>Related posts</h3>','new':''}],
               'https://www.ryanhart.org/':[{'orig':'<p>Get answers from an expert psychic today!', 'new': '<p class="remove-element">Get answers from an expert psychic today!' },
                                            {'orig': '<p>Let’s get started.</p>', 'new': ''},
                                            {'orig': '<p><strong>Read Next:</strong>', 'new': '<p class = "remove-element"><strong>Read Next:</strong>'}],
               'https://angelnumber.org': [{'orig': '<p><strong>Watch Youtube Video About Angel Number', 'new': '<p class = "remove-element"><strong>Watch Youtube Video About Angel Number'}]}
default_redirected = {'www.mindyourbodysoul.com':'https://www.mindyourbodysoul.com',
                      'www.psychnewsdaily.com': 'https://www.psychnewsdaily.com',
                      'joynumber.com': 'https://joynumber.com'}